### ISSUE TITLE
localhost:8080/payment/contract/{contractId} модель контракта в ответе

### ISSUE THREAD

**Issue by VladimirVarzov** [ivan-pukhov/government-contracts#9]
Приходит старая модель контракта
        {
            "id": 951,
            "paymentTypeId": 1,
            "paymentType": "PREPAYMENT",
            "stageId": 953,
            "contractId": 952,
            "paymentDate": "2018-05-16T13:56:39.492",
            "paymentSum": 123000.44
        },
нужно paymentTypeId моделью 
            "paymentType": {
                "id": 1,
                "code": "PREPAYMENT",
                "name": "Аванс"
            },
stageId и contractId на модели переделывать не обязательно

**Comment by ivan-pukhov** [comment]
done
